language: c

script:
- unset JRUBY_OPTS
- ./build.sh

cache: ccache

before_script: |-2
  if [[ "$(uname)" == Linux ]]; then
    echo -e "gem-wrappers\nrubygems-bundler\nbundler\nrake\nrvm\n" >> ~/.rvm/gemsets/global.gems;
    gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3;
    sudo apt-get install haveged;
    sudo service haveged start;
  fi

matrix:
  include:
  - os: linux
    sudo: required
    dist: xenial
    group: edge
  - os: linux
    sudo: required
    dist: trusty
    group: edge
  - os: osx
    before_install: sw_vers
    osx_image: xcode6.4
  - os: osx
    before_install: sw_vers
    osx_image: xcode7.2
  - os: osx
    before_install: sw_vers
    osx_image: xcode8.1

after_failure: find $rvm_path/log/ -type f | xargs ls -t | head -n 1 | xargs cat

notifications:
  email: false
