language: c

script:
- unset JRUBY_OPTS
- test -f ~/.rvmrc && cat ~/.rvmrc || true
- ./build.sh

cache: ccache

matrix:
  include:
  - arch: ppc64le
    dist: xenial
    language: bash
    before_script:
      - 'echo -e "gem-wrappers\nrubygems-bundler\nbundler\nrake\nrvm\n" >> ~/.rvm/gemsets/global.gems'
      - "gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3"

before_cache:
  - echo rvm_auto_reload_flag=1 >> ~/.rvmrc

after_failure: find $rvm_path/log/ -type f | xargs ls -t | head -n 1 | xargs cat

notifications:
  email: false
