language: c

script:
- unset JRUBY_OPTS
- ./build.sh

cache: ccache

matrix:
  include:
  - os: linux
    sudo: required
    dist: precise
    group: edge
    before_script: "gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3"
  - os: linux
    before_script:
      - 'echo -e "gem-wrappers\nrubygems-bundler\nbundler\nrake\nrvm\n" >> ~/.rvm/gemsets/global.gems'
      - "gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3"
      - "sudo apt-get install haveged"
      - "sudo service haveged start"
    services: docker
  - os: linux
    dist: xenial
    language: generic
    before_script:
      - 'echo -e "gem-wrappers\nrubygems-bundler\nbundler\nrake\nrvm\n" >> ~/.rvm/gemsets/global.gems'
      - "gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3"
      - "sudo apt-get install haveged"
      - "sudo service haveged start"
  - os: osx
    before_install: sw_vers
    osx_image: xcode6.4
  - os: osx
    before_install: sw_vers
    osx_image: xcode7.2
  - os: osx
    before_install: sw_vers
    osx_image: xcode8.1
  - os: osx
    before_install:
      - sw_vers
      - curl -sL -o gimme https://raw.githubusercontent.com/travis-ci/gimme/master/gimme
      - chmod +x gimme
      - eval $(./gimme 1.10)
    osx_image: xcode9.3beta

after_failure: find $rvm_path/log/ -type f | xargs ls -t | head -n 1 | xargs cat

notifications:
  email: false
