language: c

before_install:
- "gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3"
- rvm get head

script:
- unset JRUBY_OPTS
- ./build.sh

matrix:
  include:
  - os: linux
  - os: linux
    services: docker
    group: edge
  - os: osx
    osx_image: xcode6.4
  - os: osx
  allow_failures:
  - services: docker
  - os: osx
  fast_finish: true

after_failure: find $rvm_path/log/ -type f | xargs ls -t | head -n 1 | xargs cat

env:
  global:
    - ARTIFACTS_S3_REGION=us-east-1
    - ARTIFACTS_S3_BUCKET=travis-rubies
    - ARTIFACTS_PERMISSIONS=public-read
    - secure: "HPBQ5hUXh4vzDdZ9w8qXNsZ1x5CdYqrLyl+Mf8bzv2u429NddBnbNta8kPNyL/E9BJKTfiXPnc8HEZvR/wDVpDyZePhYcOkBzDoKhD7aPR/pjgWBkU31VHCtYIYLr9JbzV7ya6SL0Gf29C3msHirKlZBYOezMrEkEvW1JWNIEI4="
    - secure: "C5AHd2jHvmZV18uu9c7K9EreXPf1suzJA4zVTWTS7v6Rvz+bGdjsvIRnkgU1E50JU3U3mHtPta7IK5tIPVAn+83kmfdQaHrNENohf3IXiukhA3tDZiAig8ljfGI0QqME7Nel4/RV+oxXDBUbcFUBOvim5bXas93H3aBEhUYbZ8E="

notifications:
  email: false
